### ISSUE TITLE
Missing release tags

### ISSUE THREAD

**Issue by enkessler** [grange-insurance/cuke_slicer#12]
Please add a `v2.0.2` tag to commit `9283938e1777ad323fe8152bc33fdcfa05b53393`. That commit appears to be what that release was built from.

Thanks.

**Comment by enkessler** [comment]
Also add a `v2.0.3` tag to commit `e7b8fb4362dcfbd6f925919176fdd136e9bb75d2` after #13 is merged.

**Comment by dbwest** [comment]
check this is done right I did it from the GUI

**Comment by dbwest** [comment]
Take a look now, @enkessler. Thanks!

**Comment by enkessler** [comment]
Yep. Looks fine. Thanks!
