### ISSUE TITLE
Mishandling of AND/OR logic for multiple tags

### ISSUE THREAD

**Issue by pittgoose** [grange-insurance/cuke_slicer#2]
### The issue:
I'm trying to use cuke_slicer to create a list of all tests which have at least one of a set of tags and do not have any of another set of tags. Currently cuke_slicer only returns tests with _all_ of the tags passed, not tests with _any_ of the tags.

### Example:
```cucumber
Feature: This is a test file

@full_suite
Scenario: Test 1
Given foo

@continuous_deployment @full_suite
Scenario: Test 2
Given bar

@continuous_deployment
Scenario: Test 3
Given foo-bar
```
If I want to run all tests with `@full_suite` or `@continuous_deployment` I would think that I'd do:
```ruby
filters = {included_tags: ['@full_suite', '@continuous_deployment'] ,
           included_paths: [/test_directory/]}

found_tests = CukeSlicer::Slicer.new.slice(test_directory, filters, :file_line)
```
however, this results in only `Scenario: Test 2` being returned because it's only choosing scenarios with _both_ tags.

### Suggestion:
What I'd suggest doing, and this is what I might put in our code until a better solution is implemented in cuke_slicer, is use the following logical flow when preparing the list:
1. If `filters` contains `included_tags:` then perform a new `CukeSlicer::Slicer.new.slice(test_directory, filters, :file_line)` for each tag, appending the slice to the final list while removing duplicates.
2. If `filters` contains `excluded_tags:` then run through the final list from step 1 and remove tests which match any of the tags in this list.

### Additional comments:
Cucumber has the ability to exclude a tag using the tilde (ex: `~@wip`) (see [cucumber documentation](https://github.com/cucumber/cucumber/wiki/Tags)). It might be worthwhile to deprecate the `included_tags` and `excluded_tags` parameters and just a `tags` parameter which takes positive and negative tags and knows how to handle each one. Currently cuke_slicer doesn't seem to handle negative tags at all.

**Comment by ashtony42** [comment]
I'm not fond of the way it gets used either, I found it quite confusing for quite a while myself, but this feature may help with the needed input for your task:
https://github.com/grange-insurance/cuke_slicer/blob/master/features/tag_logic.feature

Using your example though will indeed get all tests with both @full_suite AND @continuous_deployment tags:
```
filters = {included_tags: ['@full_suite', '@continuous_deployment']}
```
Nested groups however get OR'd:
```
filters = {included_tags: [['@full_suite','@continuous_deployment']]}
```
Thus, the slicer is able to do complex extractions like this:

```
Feature: This is a test file

@full_suite
Scenario: Test 1
Given foo

@continuous_deployment @full_suite
Scenario: Test 2
Given bar

@continuous_deployment 
Scenario: Test 3
Given foo-bar

@full_suite @integration
Scenario: Test 4
Given food-bard

@integration @continuous_deployment 
Scenario: Test 5
Given tasteful-singer
```
```
filters = {included_tags: [['@full_suite','@continuous_deployment'],['@full_suite','@integration']]}
```
This gets understood as
(full_suite OR continuous_deployment) AND (full_suite OR integration)

And would extract Tests 2,4 and 5.

I think what you may want is the OR'd way like this:
```
filters = {included_tags: [['@full_suite','@continuous_deployment']]}
```

**Comment by enkessler** [comment]
Taking '~' on tags into account would be a handy improvement. Once that functionality is in place, it would be possible to create a tag filter for any possible tag combination that one could come up with on the command line for Cucumber.
