### ISSUE TITLE
support for cucumber 2

### ISSUE THREAD

**Issue by cartoloupe** [grange-insurance/cuke_slicer#3]
I am following the usage section in the Readme, but am running into the following error when requiring `cuke_slicer`:

```
 cartoloupe@comp  ~/repos/test_suite   update-cucumber ●  gem install cuke_slicer
Successfully installed cuke_slicer-2.0.0
Parsing documentation for cuke_slicer-2.0.0
Done installing documentation for cuke_slicer after 0 seconds
1 gem installed
 cartoloupe@comp  ~/repos/test_suite   update-cucumber ●  irb
irb(main):001:0> require 'cuke_slicer'
LoadError: cannot load such file -- gherkin/formatter/json_formatter
  from /Users/cartoloupe/.gem/ruby/2.0.0/gems/cuke_modeler-0.0.1/lib/cuke_modeler/parsing.rb:2:in `require'
  from /Users/cartoloupe/.gem/ruby/2.0.0/gems/cuke_modeler-0.0.1/lib/cuke_modeler/parsing.rb:2:in `<top (required)>'
  from /Users/cartoloupe/.gem/ruby/2.0.0/gems/cuke_modeler-0.0.1/lib/cuke_modeler.rb:3:in `require'
  from /Users/cartoloupe/.gem/ruby/2.0.0/gems/cuke_modeler-0.0.1/lib/cuke_modeler.rb:3:in `<top (required)>'
  from /Users/cartoloupe/.gem/ruby/2.0.0/gems/cuke_slicer-2.0.0/lib/cuke_slicer.rb:1:in `require'
  from /Users/cartoloupe/.gem/ruby/2.0.0/gems/cuke_slicer-2.0.0/lib/cuke_slicer.rb:1:in `<top (required)>'
  from (irb):1:in `require'
  from (irb):1
  from /Users/cartoloupe/.rubies/ruby-2.0.0-p451/bin/irb:12:in `<main>'
```

I am using cucumber version 2.3.2, and ruby 2.0.0; 

And then I searched for that error message, and it seems that maybe [the new gherkin gem that is used in the new cucumber has changed the path for its formatters](http://stackoverflow.com/questions/35698332/loaderror-cannot-load-such-file-gherkin-formatter-json-formatter-on-runnin).

**Comment by enkessler** [comment]
You are using a version of 'cuke_modeler' (upon which 'cuke_slicer' depends) that does not support newer versions of the 'gherkin' gem. You'll need to upgrade to at least 0.1.0 of 'cuke_modeler' in order to use Gherkin 3.x and at least 0.3.0 in order to use Gherkin 4.x.

**Comment by cartoloupe** [comment]
Thank you. I got the gems organized in a Gemfile and am able to load `cuke_slicer`. 👍
