### ISSUE TITLE
support for cuke_modeler 1.0.3

### ISSUE THREAD

**Issue by cartoloupe** [grange-insurance/cuke_slicer#4]
See https://github.com/enkessler/cuke_modeler/issues/3

It seems like `cuke_slicer` currently supports an older version of `cuke_modeler`, since it calls `Example#row_elements` in `https://github.com/grange-insurance/cuke_slicer/blob/fc0f2918b2b3f7e4c862579a78729e3fc6cd840f/lib/cuke_slicer/helpers/extraction_helpers.rb#L31`.

Does it make sense to upgrade `cuke_slicer` in the following way?
- [x] update the gemspec to specify a version of `cuke_modeler`
- [x] update calls to `#row_elements`
- [x] run existing tests and verify they pass

If so, I can start a PR.

**Comment by ashtony42** [comment]
I agree with you. This certainly makes sense to do. Feel free to make your pull request.

**Comment by ashtony42** [comment]
Pull Request Accepted

**Comment by enkessler** [comment]
Although the master branch has the fixes in it, a newer version of the gem has yet to be released. I'd say that this issue is still open.
