### ISSUE TITLE
Published gem is empty

### ISSUE THREAD

**Issue by enkessler** [grange-insurance/cuke_slicer#7]
It looks like version 2.0.1 has nothing in it. No idea how it happened, but here are some handy links for yanking it and publishing a new version.

http://guides.rubygems.org/command-reference/#gem-yank
http://help.rubygems.org/kb/gemcutter/removing-a-published-rubygem
http://blog.rubygems.org/2015/04/13/permadelete-on-yank.html

**Comment by dbwest** [comment]
This gem is officially released. @enkessler, please push the gem to Rubygems.

Thanks!

**Comment by enkessler** [comment]
I have published version 2.0.2 to Rubygems and yanked 2.0.1.
